spring:
  application:
    name: lovable-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/lovable?useSSL=false
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
jwt:
  secret-key: jwtsecretkeyrandom123

stripe:
  secret: STRIPE_SECRET_REMOVED

client.url: http://localhost:8080